repos:
- repo: local
  hooks:
    - id: ruff
      name: Ruff
      language: system
      entry: poetry run ruff check
      args: ["--fix", "--unsafe-fixes"]
      files: ^src/
      types: [ python ]
      stages: [ pre-commit ]
      always_run: true

    - id: black
      name: Black
      stages: [ pre-commit ]
      language: system
      entry: poetry run black
      args: ['.']
      types: [ python ]
      always_run: true

    - id: mypy
      name: Mypy
      language: system
      entry: poetry run mypy dplex
      args: [ "--config-file=pyproject.toml" ]
      types: [ python ]
      files: ^dplex/
      always_run: true

    - id: pyright
      name: Pyright
      language: system
      entry: poetry run pyright dplex
      types: [ python ]
      files: ^dplex/
      always_run: true